name: Node version
permissions:
  id-token: write  
  contents: read  
on:
  workflow_dispatch: 
  push:

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Show installed Node version
        run: |
          node --version
          npm --version
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Show installed Node version
        run: |
          node --version
          npm --version
          bdy version || true
      - name: Login to Buddy
        uses: buddy/login@v1
        with:
          token: ${{ secrets.BT }}
      - name: Show installed Node version
        run: |
          node --version
          npm --version   
          bdy version
      - name: Login to Buddy
        uses: buddy/login@v1
        with: 
          region: EU
          provider_id: 652bedb5-0c93-4cbf-bcfb-395c994bbe86






